# Steps to achieve the task:

## Step 1: download a clean Linux source tree
```bash
wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.tar.xz
```

## Step 2: Copy the files into the linux/ folder using the command below:
```bash
mkdir linux
tar -xvf linux-6.10.tar.xz -C linux --strip-components=1
```

## Step 3: Copy the linux/ directory into copied_linux/ using rsync
```bash
rsync -auv linux/ copied_linux/
```

## Step 4: I found and truncated all .c files to 0 bytes using the command below:
```bash
find copied_linux/ -name "*.c" -exec truncate -s 0 {} \;
```

## Step 5: Once the .c files are emptied, I generated a patch against the original source to make sure that the entire codebase has been included: 
```bash
diff -ruN linux/ copied_linux/ > all_diff_patch.diff
```

#### <B> Note </b>: The patch generated by the command above may not work correctly because it includes parent directory names in the file paths inside .diff file. 
<i> For example, instead of `arch/alpha/boot/bootp.c`, it results in `linux/arch/alpha/boot/bootp.c`. </i>

<pre>
diff -ruN <span style="color: #d17373;">linux/arch/alpha/boot/bootp.c</span> <span style="color: #d17373;">linux/arch/alpha/boot/bootp.c</span>
--- <span style="color: #d17373;">linux/arch/alpha/boot/bootp.c</span> 2024-09-26 21:55:19.784242880 -0400
+++ <span style="color: #d17373;">linux/arch/alpha/boot/bootp.c</span> 2024-09-28 19:30:23.700222624 -0400
</pre>


#### <b> Problem </b>: Incorrect Directory Paths in Patch File

<i> Because the `koverage` tool requires linux source directory name as input and then concatenates the source file name with the updated files, the resulting paths to be checked by the tools for validity will become even more problematic, such as:
`linux/linux/arch/alpha/boot/bootp.c`. This creates non-existent file paths, causing errors in this part of the code:
</i>

#### <b> Solution: </b> 

```bash
diff -ruN linux/ copied_linux/ | sed 's|^diff -ruN linux/|diff -ruN |; s| copied_linux/| |; s|^--- linux/|--- |; s|^+++ copied_linux/|+++ |' > all_diff_patch.diff
```

## Step 6: Input the file "all_diff_patch.diff" to the koverage tool
```bash
koverage -f --linux-ksrc /home/eshgin/koverage_task/linux --config /home/eshgin/koverage_task/linux/.config --arch x86_64 --check-patch all_diff_patch.diff -o coverage_results_all_task.json 2>&1 | tee mylogs.logs
```

## Some files caused different kinds of errors when the program ran. 
### However, at by default it was not throwing out which file caused  

These files are:
Faulty files:
1) The first faulty file was: linux/arch/powerpc/platforms/powermac/udbg_adb.c 2676 (did not truncate this one for the second run)
    The error it caused:
    ```
    Traceback (most recent call last):
      File "/home/eshgin/.local/bin/koverage", line 1120, in <module>
        main()
      File "/home/eshgin/.local/bin/koverage", line 1056, in main
        validation_covreq, validation_patch = get_validation_covreq(covreq, linux_ksrc)
      File "/home/eshgin/.local/bin/koverage", line 637, in get_validation_covreq
        cb = SyntaxAnalysis.get_conditional_blocks(content, line_count)
      File "/home/eshgin/.local/pipx/venvs/kmax/lib/python3.8/site-packages/kmax/superc.py", line 739, in get_conditional_blocks
        assert len(stack) == 1
    AssertionError
    ```
2) The second faulty file was: linux/drivers/media/pci/cx23885/netup-eeprom.c 43023 (did not truncate this one for the third run)
    The error it caused:
    ```
    Traceback (most recent call last):
      File "/home/eshgin/.local/bin/koverage", line 1120, in <module>
        main()
      File "/home/eshgin/.local/bin/koverage", line 1056, in main
        validation_covreq, validation_patch = get_validation_covreq(covreq, linux_ksrc)
      File "/home/eshgin/.local/bin/koverage", line 637, in get_validation_covreq
        cb = SyntaxAnalysis.get_conditional_blocks(content, line_count)
      File "/home/eshgin/.local/pipx/venvs/kmax/lib/python3.8/site-packages/kmax/superc.py", line 702, in get_conditional_blocks
        next_token_to_type = categorized_tokens[linenum][i + 1]
    ```
3) The third faulty file was: drivers/net/can/mscan/mscan.c 49128
    
4) The fourth faulty file was: drivers/net/ethernet/i825xx/sun3_82586.c 50937 The error it caused:
    ```
    Traceback (most recent call last):
      File "/home/eshgin/.local/bin/koverage", line 1120, in <module>
        main()
      File "/home/eshgin/.local/bin/koverage", line 1056, in main
        validation_covreq, validation_patch = get_validation_covreq(covreq, linux_ksrc)
      File "/home/eshgin/.local/bin/koverage", line 637, in get_validation_covreq
        cb = SyntaxAnalysis.get_conditional_blocks(content, line_count)
      File "/home/eshgin/.local/pipx/venvs/kmax/lib/python3.8/site-packages/kmax/superc.py", line 715, in get_conditional_blocks
        stack[-1].sub_block_groups.append([new_cb])
    IndexError: list index out of range
    ```
diff -ruN init/init_task.c init/init_task.c 19668451
5) The fifth faulty file was: init/main.c 9012782 in .diff (28167 after truncation) The error it caused:
    Traceback (most recent call last):
      File "/home/eshgin/.local/bin/koverage", line 1120, in <module>
        main()
      File "/home/eshgin/.local/bin/koverage", line 1056, in main
        validation_covreq, validation_patch = get_validation_covreq(covreq, linux_ksrc)
      File "/home/eshgin/.local/bin/koverage", line 637, in get_validation_covreq
        cb = SyntaxAnalysis.get_conditional_blocks(content, line_count)
      File "/home/eshgin/.local/pipx/venvs/kmax/lib/python3.8/site-packages/kmax/superc.py", line 739, in get_conditional_blocks
        assert len(stack) == 1
    AssertionError
6) The sixty faulty file was: drivers/gpu/drm/omapdrm/omap_dmm_tiler.c 10442
    The error it caused:
    Traceback (most recent call last):
  File "/home/eshgin/.local/bin/koverage", line 1115, in <module>
    main()
  File "/home/eshgin/.local/bin/koverage", line 1051, in main
    validation_covreq, validation_patch = get_validation_covreq(covreq, linux_ksrc)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eshgin/.local/bin/koverage", line 632, in get_validation_covreq
    cb = SyntaxAnalysis.get_conditional_blocks(content, line_count)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eshgin/.local/share/pipx/venvs/kmax/lib/python3.12/site-packages/kmax/superc.py", line 737, in get_conditional_blocks
    assert len(stack) == 1


1) arch/alpha/kernel/ptrace.c caused error afterwards:
    stderr: "b"patch: **** Can't rename file arch/alpha/kernel/ptrace.c.ohBGgHS to arch/alpha/kernel/ptrace.c : Too many open files\n"". in folder: error2
    


When I omitted the lines before init/main.c, the output was a json file, but when I included all the lines, there were not happening any errors but output file was not present




diff -ruN drivers/net/ethernet/i825xx/sni_82596.c


koverage -f --linux-ksrc /home/eshgin/Desktop/koverage_task/linux --config /home/eshgin/Desktop/koverage_task/linux/.config --arch x86_64 --check-patch fw_all_diff_patch.diff -o /home/eshgin/Desktop/koverage_task/coverage_results_all_task_working.json 2>&1 | tee all_working_logs.log


